
#ifndef GLOBUS_XIO_GRIDFTP_MULTICAST_DRIVER_INCLUDE
#define GLOBUS_XIO_GRIDFTP_MULTICAST_DRIVER_INCLUDE

#include "globus_xio_system.h"
#include "globus_common.h"

typedef enum
{
    GLOBUS_XIO_GRIDFTP_MULTICAST_ERROR_NOOP,
    GLOBUS_XIO_GRIDFTP_MULTICAST_ERROR_TRANSFER_FAILURES
} globus_xio_gridftp_multicast_error_type_t;

enum
{
    GLOBUS_XIO_GRIDFTP_MULTICAST_ATTR_PARALLEL = 1,
    GLOBUS_XIO_GRIDFTP_MULTICAST_ATTR_TCPBS,
    GLOBUS_XIO_GRIDFTP_MULTICAST_ATTR_URLS,
    GLOBUS_XIO_GRIDFTP_MULTICAST_ATTR_LOCAL_WRITE,
    GLOBUS_XIO_GRIDFTP_MULTICAST_ATTR_CAST_COUNT,
    GLOBUS_XIO_GRIDFTP_MULTICAST_ATTR_SUBJECT
};

#endif
