#! /usr/bin/perl

use strict;
use Cwd;
use File::Basename;
use Getopt::Long;
use lib dirname($0);

require 5.8.0;
use vars qw(@tests);

$ENV{GLOBUS_USAGE_OPTOUT} = "1";

my $server_pid;
my $server_prog = $ENV{GRIDFTP_EXE} || "globus-gridftp-server";
my $server_host = "localhost";
my $server_port = 0;
my $server_nosec = "-auth-level 4";
my $subject;

my $server_args = "-no-chdir -d 0 -p $server_port $server_nosec";
if ($< != 0) {
    $server_args = "-no-fork $server_args";
}
chomp($subject = `openssl x509 -in testcred.cert -subject -noout -nameopt rfc2253,-dn_rev`);
$subject =~ s/^subject= */\//;
$subject =~ s/,/\//g;

$server_pid = open(SERVER, "$server_prog $server_args |");
 
if($server_pid == -1)
{
    print "Unable to start server\n";
    exit 1;
}

select((select(SERVER), $| = 1)[0]);
$server_port = <SERVER>;
$server_port =~ s/Server listening at .*?:(\d+)/\1/;
chomp($server_port);

if($server_port !~ /\d+/)
{
    print "Unable to start server\n";
    exit 1;
}

$ENV{GLOBUS_FTP_SUBJECT} = $subject;
$ENV{GLOBUS_FTP_CONTACT} = "gsiftp://$server_host:$server_port";

print STDERR "#". join(" ", @ARGV, "\n");      
my $rc = system(@ARGV);
print STDERR "# Test exited with $rc\n";

kill 'INT', $server_pid;

if (kill 0, $server_pid) {
    sleep(1);
    if (kill 0, $server_pid) {
        kill 'KILL', $server_pid;
    }
}
exit ($rc!=0);
