#ifndef GLOBUS_XIO_UDT_REF_H
#define GLOBUS_XIO_UDT_REF_H

enum
{
    GLOBUS_XIO_UDT_MSS = 1,
    GLOBUS_XIO_UDT_SNDSYN,
    GLOBUS_XIO_UDT_RCVSYN,
    GLOBUS_XIO_UDT_FC,  
    GLOBUS_XIO_UDT_SNDBUF,  
    GLOBUS_XIO_UDT_RCVBUF, 
    GLOBUS_XIO_UDT_UDP_SNDBUF,  
    GLOBUS_XIO_UDT_UDP_RCVBUF, 
    GLOBUS_XIO_UDT_LINGER,  
    GLOBUS_XIO_UDT_RENDEZVOUS, 
    GLOBUS_XIO_UDT_SNDTIMEO,  
    GLOBUS_XIO_UDT_RCVTIMEO, 
    GLOBUS_XIO_UDT_REUSEADDR,
    GLOBUS_XIO_UDT_SET_LOCAL_PORT,
    GLOBUS_XIO_UDT_GET_LOCAL_PORT,
    GLOBUS_XIO_UDT_SET_FD,
    GLOBUS_XIO_UDT_GET_LOCAL_CANDIDATES,
    GLOBUS_XIO_UDT_SET_REMOTE_CANDIDATES
};

#endif
