#! /usr/bin/perl

use strict;
use Cwd;
use File::Basename;
use Getopt::Long;
use lib dirname($0);
use FtpTestLib;

require 5.8.0;
use vars qw(@tests);

$ENV{GLOBUS_USAGE_OPTOUT} = "1";
$ENV{FTP_TEST_FORCE_LOCAL} = "1";
my $server_pid;
my $server_prog = $ENV{GRIDFTP_SERVER_EXE} || "globus-gridftp-server";
my $server_host = "localhost";
my $subject;

my $server_args = "-no-chdir -no-exit -d 0 -auth-level 4 -p 0";
if ($< != 0)
{
    $server_args = "-no-fork $server_args";
}

chomp($subject = `openssl x509 -subject -noout -in \${X509_USER_CERT:-testcred.cert} -nameopt rfc2253,-dn_rev`);
$subject =~ s/^subject= */\//;
$subject =~ s/,/\//g;

print STDERR "#Subject is $subject\n";
print STDERR "#PATH is $ENV{PATH}\n";
print STDERR "#executing $server_prog $server_args\n";
#$server_pid = open(SERVER, "../libtool --mode=execute valgrind --log-file=valgrind.log.%p       --trace-children=yes $server_prog $server_args |");
$server_pid = open(SERVER, "$server_prog $server_args |");
 
if($server_pid == -1)
{
    print "Unable to start server\n";
    exit 99;
}

select((select(SERVER), $| = 1)[0]);
my $server_port = <SERVER>;
$server_port =~ s/Server listening at .*?:(\d+)/\1/;
$server_port =~ s/\s*$//;

if($server_port !~ /\d+/)
{
    print "Unable to start server: $server_port\n";
    exit 1;
}

print "Started server at port $server_port\n";

# sleep a second, some hosts are slow....

sleep 5;

$ENV{GLOBUS_FTP_CLIENT_TEST_SUBJECT} = $subject;
$ENV{FTP_TEST_SOURCE_HOST} = "$server_host:$server_port";
$ENV{FTP_TEST_DEST_HOST} = "$server_host:$server_port";   

my $rc = system(@ARGV);
print "Test exited with $rc\n";

kill 'INT', $server_pid;

if (kill 0, $server_pid) {
    sleep(1);
    if (kill 0, $server_pid) {
        kill 'KILL', $server_pid;
    }
}

exit ($rc>>8);
